### ISSUE TITLE
mojo error

### ISSUE THREAD

**Issue by noorullap** [simpligility/maven-android-sdk-deployer#268]
@rtack 
@royclarkson 
@yuvipanda 
@mingfai 
@shairontoledo 
Failed to execute goal org.codehaus.mojo:properties-maven-plugin:1.0-alpha-2:read-project-properties (default) on project google-apis-3: Properties file not found: /Volumes/NOOR/Download/adt-bundle-mac-x86_64-20140702/sdk/add-ons/addon-google_apis-google-3/source.properties -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :google-apis-3

**Comment by benelliott** [comment]
Are you sure you have installed the Google APIs add-on for API level 3 (Android 1.5) through your SDK Manager?
