### ISSUE TITLE
Individual Play-Services APIs

### ISSUE THREAD

**Issue by Stuey86** [simpligility/maven-android-sdk-deployer#270]
Will the Individual Play-Services API aars be included in a future release to be uploaded to a Central Repo?

%ANDROID_HOME%\extras\google\m2repository\com\google\android\gms\play-services-maps

http://developer.android.com/google/play-services/setup.html - Table 1

Google+	com.google.android.gms:play-services-plus:6.5.87
Google Account Login	com.google.android.gms:play-services-identity:6.5.87
Google Activity Recognition	com.google.android.gms:play-services-location:6.5.87
etc..

**Comment by william-ferguson-au** [comment]
Not sure what you are asking @Stuey86 

Using the maven-android-sdk-deployer you can deploy to your hosted repository.
But the maven-android-sdk-deployer project doesn't own the Google Play-Services  artifacts and cannot deploy them to Maven Central. For that you need to pressure Google.

**Comment by Stuey86** [comment]
Hi @william-ferguson-au 

I was asking about the maven-android-sdk-deployer to a private Nexus Repo, not Central
The Deployer currently only deploys the All inclusive Play Services API, but not the individual API's so that i can only include the API's I need. e.g.

<dependency>
  <groupId>com.google.android.gms</groupId>
  <artifactId>play-services-maps</artifactId>
  <version>6.5.87</version>
</dependency>

I have to manually install the Files each time. 

Thanks

**Comment by william-ferguson-au** [comment]
Do you mean the artifacts that are shipped in the 2 Maven repos within the Android SDK?

Just create a hosted Nexus repo that points to each location. There's no need for the maven-sdk-deployer to do anything.

**Comment by mosabua** [comment]
@william-ferguson-au @Stuey86 the Maven repositories from the the SDK are also installed or deployed by the Maven Android SDK Deployer.. using a hosted Nexus instance where the storage points to the SDK is a suboptimal solution that only works with Nexus. 

Better create an Android repository for all the deployer tools. Set it to allow redeploys. And run the deployer into it regularly (whenever you update the SDK basically).

Now in terms of these additional artifacts.. where are they in the SDK?

**Comment by Stuey86** [comment]
@mosabua The additional Artifacts are the split up Play Services found here %ANDROID_HOME%\android-sdk\extras\google\m2repository\com\google\android\gms

**Comment by mosabua** [comment]
@Stuey86 all the artifacts in the m2repository are installed/deployed with the Maven Android SDK Deployer so you should be okay..

**Comment by Stuey86** [comment]
Thanks @mosabua . Finally got a chance to check it out. :) works great
Do you also have a problem where the API Artficats (play-services-maps, play-services-location, etc..)  reference the play-services-base 6.5.87 as a JAR but the actual artifact is an AAR

**Comment by william-ferguson-au** [comment]
Stuey that is a problem with the way that AAR libraries with AAR
dependencies (deployed in the Android) have been packaged.
See
http://design-counts.blogspot.com.au/2014/11/handling-missing-android-support-v420.html

And feel free to star
https://code.google.com/p/android/issues/detail?id=72807

William
ᐧ
