### ISSUE TITLE
pom.sha1 and jar.sha1 files don't exist

### ISSUE THREAD

**Issue by sobhanattar** [simpligility/maven-android-sdk-deployer#274]
Hi
Thanks for this great library. There is one problem I have with this library is that it doesn't create sha1 files of jar and pom. we need these files as we don't want maven to go for downloading these files as they're not anywhere on the web.

Should we create them manually or it can be handled by the library itself.
Thanks in advance

**Comment by Shusshu** [comment]
Maybe this could be used: http://nicoulaj.github.io/checksum-maven-plugin/index.html or something else...

Can you have a try and make a pull request?

**Comment by mosabua** [comment]
Uploading them to a repo manager will automatically create the checksums. For a local repositiory there is no real use case to have them.

**Comment by Shusshu** [comment]
Didn't know that. cool cool that's why I also have them :)
We can close this I guess
