### ISSUE TITLE
Build a plugin

### ISSUE THREAD

**Issue by KleinerHacker** [simpligility/maven-android-sdk-deployer#278]
Hi,
a very better solution to use it is to create a maven plugin to do that automatically each build in developers project for the needed artifacts. 
So it is possible for other developers to check out the source code and build the project directly without using the 'helper-project' explicitly. This is an easier way for all.

**Comment by mosabua** [comment]
Haha... yes, of course. We have known that for a long time. However nobody wrote that plugin. I am in the process of creating a library for doing that (https://github.com/simpligility/maven-repository-tools) and then create a goal in the android-maven-plugin to do that. 

If you want to help working on that, let me know.
