### ISSUE TITLE
Android 6.0

### ISSUE THREAD

**Issue by devemux86** [simpligility/maven-android-sdk-deployer#282]
Trying to install Android 6.0 the build fails because it cannot find ```add-ons/google-apis-23``` child module as defined in ```add-ons/pom.xml```.

**Comment by bstrawson** [comment]
Confirmed - seeing the same issue here.

**Comment by Shusshu** [comment]
mmmm that's weird why didn't it get added to git with `git add -A`

I'm looking into it now

**Comment by Shusshu** [comment]
can you try now?

**Comment by Shusshu** [comment]
Ok I deleted it by accident
https://github.com/simpligility/maven-android-sdk-deployer/commit/0db16ea1d79233b02164c2c42f3146df12dfe00e#diff-cf1c39e373660500c8af8ce474ea2ff1

**Comment by devemux86** [comment]
Yes now the build works, thanks!

**Comment by bstrawson** [comment]
That's fixed it - thanks.
