### ISSUE TITLE
thank you for this plugin ,it help me to create android app with maven!

### ISSUE THREAD

**Issue by wsdjeg** [simpligility/maven-android-sdk-deployer#287]
here is a problem i just fix , i think should add to readme,the dependency groupId should not be write as com.google.android
https://github.com/artur-shaik/vim-javacomplete2/issues/115#issuecomment-149435720

**Comment by mattn** [comment]
it's not problem of this plugin, maybe.

**Comment by wsdjeg** [comment]
yes ,but as old Tutorial the groupid is com.google.android
