### ISSUE TITLE
 com.simpligility.android.sdk-deployer:android-extras:pom:2.7.0 i

### ISSUE THREAD

**Issue by fyname** [simpligility/maven-android-sdk-deployer#291]
Non-resolvable parent POM: Failure to find com.simpligility.android.sdk-deployer:android-extras:pom:2.7.0 in http://192.168.1.119/nexus/content/groups/publicr/ was cached in the local repository, resolution will not be reattempted until the update interval of publicr has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 9, column 13 -> [Help 2]

update：
 com.simpligility.android.sdk-deployer:android-extras:pom:2.8.0 
is ok

**Comment by marekciupak** [comment]
> com.simpligility.android.sdk-deployer:android-extras:pom:2.8.0 is ok

Thanks for this. I had the same problem :)

**Comment by secondsun** [comment]
As I commented in #293, Google has removed the play services libproject from the SDK.

**Comment by mosabua** [comment]
Removed the extras module from defaults.
