### ISSUE TITLE
Why are this packages not on Maven Central

### ISSUE THREAD

**Issue by reiz** [simpligility/maven-android-sdk-deployer#296]
Why I need to download a whole IDE before I can pull in JAR files into my local MVN directory. Why are not all this JAR files publicly available on Maven Central? This whole process is super complicated and just makes the whole dev. process not enjoyable at all.

**Comment by kovmarci86** [comment]
Hi, its most probably because you need to accept the license to have the jars, inside the SDK or IDE you have. After that you can deploy them locally. Maven central has its own requirements for the licesnse of the deployed artifacts, which differs from what Android is using.

**Comment by mosabua** [comment]
Because Google forces the EULA on SDK users and is not willing to push the artifacts to the Central Repository. I worked towards that with the Android SDK team years ago but it was essentially blocked for legal issues.

**Comment by reiz** [comment]
@mosabua @kovmarci86 Ok. That makes sense. Many thanks for the explanation.
