### ISSUE TITLE
how to add manifestPlaceholders in manifestMerger

### ISSUE THREAD

**Issue by su1216** [simpligility/maven-android-sdk-deployer#299]
I try to exec: mvn package Dc=PC and channel config in my AndroidManifest is like <meta-data android:value="${c}" android:name="CHANNEL"/>

then I got an error : Attribute application@label at AndroidManifest.xml:41:13-33 requires a placeholder substitution but no value for <c> is provided.

**Comment by mosabua** [comment]
Not related to the deployer
