### ISSUE TITLE
env.ANDROID_HOME not work!

### ISSUE THREAD

**Issue by JiaDuo** [simpligility/maven-android-sdk-deployer#304]
in pom.xml  I see:
<android.sdk.path>${env.ANDROID_HOME}</android.sdk.path>
I follow the README file but not work, because "android.sdk.path" can't be set.

so i change the line to 
<android_sdk_path>${env.ANDROID_HOME}</android_sdk_path> 
it works

**Comment by mosabua** [comment]
Not sure.. it all works for us.
