### ISSUE TITLE
Support for API level 26?

### ISSUE THREAD

**Issue by alixwar** [simpligility/maven-android-sdk-deployer#305]
The current project does not support Android Oreo / API 26

**Comment by Shusshu** [comment]
I will gladly merge your PR adding support for API 26 (Don't forget to change the changelog with your name)

**Comment by alixwar** [comment]
Here is the PR: https://github.com/simpligility/maven-android-sdk-deployer/pull/306

I haven't tried it myself yet (not possible where I'm at)
