### ISSUE TITLE
Question: Project obsolete?

### ISSUE THREAD

**Issue by alixwar** [simpligility/maven-android-sdk-deployer#307]
When preparing for Android Oreo I stumbled on this information:

```
// REQUIRED: Google's new Maven repo is required for the latest
// support library that is compatible with Android 8.0
repositories {
    maven {
        url 'https://maven.google.com'
        // Alternative URL is 'https://dl.google.com/dl/android/maven2/'
    }
}
```
Source: https://developer.android.com/about/versions/oreo/android-8.0-migration.html

Does this mean that there is no use anymore for maven-android-sdk-deployer?

**Comment by mosabua** [comment]
Both of those URLs do NOT contain any maven repo that is browsable from all I can tell. Until those actually work the deployer is still needed.

**Comment by alixwar** [comment]
It's odd that it's not browsable, but it seems to work (at least for support libraries). But as there is uncertainty as to what is actually in there I would agree for now.

**Comment by mosabua** [comment]
Sigh.. if you cant browse it .. how are you going to know whats in it..

**Comment by alixwar** [comment]
I referenced it through a proxy (Nexus) and was able to fetch the dependencies that I wanted from it. But I'm no Maven repository expert and not eager on learning more at the moment so until any new information comes up we can assume that this project is needed

**Comment by Shusshu** [comment]
Android Studio let the user know if his version is not the latest so we can already use that repo but I also think we should be able to browse iy
